name: Build release

on:
  release:
    types: [published]

jobs:
  windows:
    runs-on: windows-2019
    name: Build Windows
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Create package
        run: |
          npm run dist
          mkdir actions
          cp dist/YANBFGenerator.exe actions/YANBF-GUI.exe
        shell: bash
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: actions
          name: YANBF-GUI-Windows

  macos:
    runs-on: macos-11
    name: Build macOS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Create package
        run: |
          npm run dist
          mkdir actions
          cp dist/YANBFGenerator.dmg actions/YANBF-GUI.dmg
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: actions
          name: YANBF-GUI-macOS

  linux:
    runs-on: ubuntu-latest
    name: Build Linux
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Create package
        run: |
          npm run dist
          mkdir actions
          cp dist/YANBFGenerator.AppImage actions/YANBF-GUI.AppImage
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: actions
          name: YANBF-GUI-Linux

  release:
    runs-on: ubuntu-latest
    name: Release
    if: ${{ success() }}
    needs: [macos, windows, linux]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            YANBF-GUI-Windows/YANBF-GUI.exe
            YANBF-GUI-macOS/YANBF-GUI.dmg
            YANBF-GUI-Linux/YANBF-GUI.AppImage
